#!/bin/bash

echo "🚀 Cocode - Push to GitHub"
echo "=================================="
echo ""

echo "📋 Steps to push to GitHub:"
echo ""
echo "1. Go to https://github.com and create a new repository:"
echo "   - Repository name: cocode"
echo "   - Description: AI-assisted IDE that promotes critical thinking and codebase familiarity"
echo "   - Choose Public or Private"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo ""

echo "2. After creating the repository, copy the repository URL"
echo "   (It will look like: https://github.com/yourusername/cocode.git)"
echo ""

echo "3. Run these commands to push your code:"
echo ""
echo "   # Add the remote repository (replace with your actual URL):"
echo "   git remote add origin https://github.com/yourusername/cocode.git"
echo ""
echo "   # Push the code to GitHub:"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "4. Your repository will be live at:"
echo "   https://github.com/yourusername/cocode"
echo ""

echo "🎉 That's it! Your Cocode IDE is now on GitHub!"
echo ""
echo "📝 Don't forget to:"
echo "   - Update the repository description"
echo "   - Add topics/tags: ide, ai, learning, typescript, react"
echo "   - Enable GitHub Pages if you want to deploy it"
echo "   - Add a license file"
echo ""

echo "🔗 Quick links after pushing:"
echo "   - Repository: https://github.com/yourusername/cocode"
echo "   - Clone URL: https://github.com/yourusername/cocode.git"
echo "   - Issues: https://github.com/yourusername/cocode/issues"
echo ""
